spring:
  config:
    name: project2
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: 123456789
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop

    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql:
        default_schema:
    generate-ddl: on


  sql:
    init:
      mode: always

server:
  port: 8888


